// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGGoMu51tRWrpyfxLMbaA2pz4Vnna9qMw',
    appId: '1:56664279631:web:775d0c58dc0da3bfc4b83a',
    messagingSenderId: '56664279631',
    projectId: 'stocks-a0603',
    authDomain: 'stocks-a0603.firebaseapp.com',
    storageBucket: 'stocks-a0603.firebasestorage.app',
    measurementId: 'G-MYLBJS445C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-gvQADSgHC5sXnXDMVrqkUSwCkwItGJA',
    appId: '1:56664279631:android:c13f0f1e1de9febdc4b83a',
    messagingSenderId: '56664279631',
    projectId: 'stocks-a0603',
    storageBucket: 'stocks-a0603.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_3eTShP3I1BnCDgefNv-QP5WymRLNNsA',
    appId: '1:56664279631:ios:9d28c8a08ccfafe6c4b83a',
    messagingSenderId: '56664279631',
    projectId: 'stocks-a0603',
    storageBucket: 'stocks-a0603.firebasestorage.app',
    androidClientId: '56664279631-mqaema0mcebf0a1gjqbkkgvvohu0lsnj.apps.googleusercontent.com',
    iosClientId: '56664279631-k07c1rncopqihrktt8eptsj94tdum9io.apps.googleusercontent.com',
    iosBundleId: 'com.example.stocks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_3eTShP3I1BnCDgefNv-QP5WymRLNNsA',
    appId: '1:56664279631:ios:9d28c8a08ccfafe6c4b83a',
    messagingSenderId: '56664279631',
    projectId: 'stocks-a0603',
    storageBucket: 'stocks-a0603.firebasestorage.app',
    androidClientId: '56664279631-mqaema0mcebf0a1gjqbkkgvvohu0lsnj.apps.googleusercontent.com',
    iosClientId: '56664279631-k07c1rncopqihrktt8eptsj94tdum9io.apps.googleusercontent.com',
    iosBundleId: 'com.example.stocks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGGoMu51tRWrpyfxLMbaA2pz4Vnna9qMw',
    appId: '1:56664279631:web:176dfa19e5760057c4b83a',
    messagingSenderId: '56664279631',
    projectId: 'stocks-a0603',
    authDomain: 'stocks-a0603.firebaseapp.com',
    storageBucket: 'stocks-a0603.firebasestorage.app',
    measurementId: 'G-WDR4G9YVE6',
  );

}